//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infragistics.Practices.CompositeUI.WinForms.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Infragistics.Practices.CompositeUI.WinForms.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The adapter is already associated with an invoker..
        /// </summary>
        internal static string AdapterAlreadyHasInvoker {
            get {
                return ResourceManager.GetString("AdapterAlreadyHasInvoker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tool cannot be a &apos;TaskPaneTool&apos;..
        /// </summary>
        internal static string CannotAcceptTaskPaneTool {
            get {
                return ResourceManager.GetString("CannotAcceptTaskPaneTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        internal static string Category_Appearance {
            get {
                return ResourceManager.GetString("Category_Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behavior.
        /// </summary>
        internal static string Category_Behavior {
            get {
                return ResourceManager.GetString("Category_Behavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Composite UI.
        /// </summary>
        internal static string Category_CompositeUI {
            get {
                return ResourceManager.GetString("Category_CompositeUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout.
        /// </summary>
        internal static string Category_Layout {
            get {
                return ResourceManager.GetString("Category_Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The image to be displayed for the smart part in the associated workspace..
        /// </summary>
        internal static string Desc_ImageSmartPartInfo_Image {
            get {
                return ResourceManager.GetString("Desc_ImageSmartPartInfo_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The default location for the dock area created to contain the smart part if the &apos;PreferredGroup&apos; is not located..
        /// </summary>
        internal static string Desc_UltraDockSmartPartInfo_DefaultLocation {
            get {
                return ResourceManager.GetString("Desc_UltraDockSmartPartInfo_DefaultLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The style of the dockarea pane created to contain the smart part if the &apos;PreferredGroup&apos; is not located..
        /// </summary>
        internal static string Desc_UltraDockSmartPartInfo_DefaultPaneStyle {
            get {
                return ResourceManager.GetString("Desc_UltraDockSmartPartInfo_DefaultPaneStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key of the group to which the pane containing the smart part should be added..
        /// </summary>
        internal static string Desc_UltraDockSmartPartInfo_PreferredGroup {
            get {
                return ResourceManager.GetString("Desc_UltraDockSmartPartInfo_PreferredGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The size at which the pane containing the smart part should be created..
        /// </summary>
        internal static string Desc_UltraDockSmartPartInfo_PreferredSize {
            get {
                return ResourceManager.GetString("Desc_UltraDockSmartPartInfo_PreferredSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An UltraDockManager that provides workspace infrastructure for use with CAB..
        /// </summary>
        internal static string Desc_UltraDockWorkspace {
            get {
                return ResourceManager.GetString("Desc_UltraDockWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An UltraExplorerBar that provides workspace infrastructure for use with CAB..
        /// </summary>
        internal static string Desc_UltraExplorerBarWorkspace {
            get {
                return ResourceManager.GetString("Desc_UltraExplorerBarWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key of the group to which the tab containing the smart part should be added..
        /// </summary>
        internal static string Desc_UltraMdiTabSmartPartInfo_PreferredGroup {
            get {
                return ResourceManager.GetString("Desc_UltraMdiTabSmartPartInfo_PreferredGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An UltraTabbedMdiManager that provides workspace infrastructure for use with CAB..
        /// </summary>
        internal static string Desc_UltraMdiTabWorkspace {
            get {
                return ResourceManager.GetString("Desc_UltraMdiTabWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates whether the tab should be activated when shown..
        /// </summary>
        internal static string Desc_UltraTabSmartPartInfo_ActivateTab {
            get {
                return ResourceManager.GetString("Desc_UltraTabSmartPartInfo_ActivateTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An UltraTabControl that provides workspace infrastructure for use with CAB..
        /// </summary>
        internal static string Desc_UltraTabWorkspace {
            get {
                return ResourceManager.GetString("Desc_UltraTabWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An UltraToolbarsManager that provides workspace infrastructure for use with CAB..
        /// </summary>
        internal static string Desc_UltraToolbarsManagerWorkspace {
            get {
                return ResourceManager.GetString("Desc_UltraToolbarsManagerWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text displayed in the task pane toolbar when the smart part is activated. By default, the &apos;Title&apos; will be displayed..
        /// </summary>
        internal static string Desc_UltraToolbarsSmartPartInfo_HeaderCaption {
            get {
                return ResourceManager.GetString("Desc_UltraToolbarsSmartPartInfo_HeaderCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determine where the task pane toolbar will be docked if one is created to display the smart part..
        /// </summary>
        internal static string Desc_UltraToolbarsSmartPartInfo_PreferredDockedLocation {
            get {
                return ResourceManager.GetString("Desc_UltraToolbarsSmartPartInfo_PreferredDockedLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DockedContentExtent used for the task pane toolbar if one is created to display the smart part..
        /// </summary>
        internal static string Desc_UltraToolbarsSmartPartInfo_PreferredExtent {
            get {
                return ResourceManager.GetString("Desc_UltraToolbarsSmartPartInfo_PreferredExtent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determine whether the task pane toolbar will display the navigation buttons if one is created to display the smart part..
        /// </summary>
        internal static string Desc_UltraToolbarsSmartPartInfo_PreferredNavigationStyle {
            get {
                return ResourceManager.GetString("Desc_UltraToolbarsSmartPartInfo_PreferredNavigationStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determine whether the task pane toolbar will display the home button if one is created to display the smart part..
        /// </summary>
        internal static string Desc_UltraToolbarsSmartPartInfo_PreferredShowHomeButton {
            get {
                return ResourceManager.GetString("Desc_UltraToolbarsSmartPartInfo_PreferredShowHomeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key of the task pane toolbar in which to display the smart part; otherwise the key of the task pane toolbar created..
        /// </summary>
        internal static string Desc_UltraToolbarsSmartPartInfo_PreferredTaskPane {
            get {
                return ResourceManager.GetString("Desc_UltraToolbarsSmartPartInfo_PreferredTaskPane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates how the smart part should be resized when the associated task pane tool is selected or the containing task pane toolbar is resized..
        /// </summary>
        internal static string Desc_UltraToolbarsSmartPartInfo_ResizeMode {
            get {
                return ResourceManager.GetString("Desc_UltraToolbarsSmartPartInfo_ResizeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoked when a smart part within the workspace is activated..
        /// </summary>
        internal static string Desc_Workspace_E_SmartPartActivated {
            get {
                return ResourceManager.GetString("Desc_Workspace_E_SmartPartActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelable event that occurs when a smart part within the workspace is about to be closed..
        /// </summary>
        internal static string Desc_Workspace_E_SmartPartClosing {
            get {
                return ResourceManager.GetString("Desc_Workspace_E_SmartPartClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The adapter is not associated with the specified invoker..
        /// </summary>
        internal static string DifferentInvoker {
            get {
                return ResourceManager.GetString("DifferentInvoker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified uielement type &apos;{0}&apos; is not a valid for the &apos;{1}&apos;..
        /// </summary>
        internal static string InvalidAdapterElementType {
            get {
                return ResourceManager.GetString("InvalidAdapterElementType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified adapter is not associated with the specified key..
        /// </summary>
        internal static string InvalidAdapterForKey {
            get {
                return ResourceManager.GetString("InvalidAdapterForKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; cannot host uielements..
        /// </summary>
        internal static string InvalidElementHost {
            get {
                return ResourceManager.GetString("InvalidElementHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to access the specified event for the specified invoker..
        /// </summary>
        internal static string InvalidInvokerEvent {
            get {
                return ResourceManager.GetString("InvalidInvokerEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoker is not of type &apos;{0}&apos;..
        /// </summary>
        internal static string InvalidInvokerType {
            get {
                return ResourceManager.GetString("InvalidInvokerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The owner of the specified tools collection must be a PopupMenuTool, RibbonGroup, ApplicationMenuArea, or UltraToolbarBase..
        /// </summary>
        internal static string InvalidToolsCollectionForElements {
            get {
                return ResourceManager.GetString("InvalidToolsCollectionForElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;MdiParent&apos; property must be set to the mdi parent form..
        /// </summary>
        internal static string MdiParentNotSet {
            get {
                return ResourceManager.GetString("MdiParentNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;RibbonTab&apos; must be part of the ContextualTabGroup&apos;s Tabs collection..
        /// </summary>
        internal static string TabNotPartOfContextualTabGroup {
            get {
                return ResourceManager.GetString("TabNotPartOfContextualTabGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tools collection must be associated with an UltraToolbarsManager..
        /// </summary>
        internal static string ToolsCollectionNotPartOfManager {
            get {
                return ResourceManager.GetString("ToolsCollectionNotPartOfManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified smart part is not docked within the {0}..
        /// </summary>
        internal static string UltraDockWorkspace_MissingSmartPart {
            get {
                return ResourceManager.GetString("UltraDockWorkspace_MissingSmartPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The adapter key is not recognized..
        /// </summary>
        internal static string UnrecognizedAdapterKey {
            get {
                return ResourceManager.GetString("UnrecognizedAdapterKey", resourceCulture);
            }
        }
    }
}
